# Generated by Django 3.0.7 on 2020-08-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200816_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='tip',
        ),
    ]
