# Generated by Django 3.0.7 on 2020-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_urun_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='tip',
            field=models.CharField(blank=True, choices=[('Menu', 'Menu'), ('Kahvalti', 'Kahvalti'), ('Diger', 'Diger')], max_length=10),
        ),
    ]
