# Generated by Django 3.0.7 on 2020-08-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_urun_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='tip',
            field=models.CharField(blank=True, choices=[('Menu', 'Menu'), ('Kahvalti', 'Kahvalti'), ('Icecek', 'Icecek'), ('Diger', 'Diger')], max_length=10),
        ),
    ]
