# Generated by Django 3.0.7 on 2020-08-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20200817_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='urun',
        ),
    ]
