# Generated by Django 3.0.7 on 2020-08-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200818_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
