# Generated by Django 3.0.7 on 2020-08-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200818_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
