# Generated by Django 3.0.7 on 2020-08-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20200818_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categori',
            name='tip',
            field=models.CharField(blank=True, choices=[('menu', 'menu'), ('categori', 'categori')], max_length=10),
        ),
        migrations.AlterField(
            model_name='urun',
            name='tip',
            field=models.CharField(blank=True, choices=[('menu', 'menu'), ('Kahvalti', 'Kahvalti'), ('Icecek', 'Icecek'), ('Diger', 'Diger')], max_length=10),
        ),
    ]
