# Generated by Django 3.0.7 on 2020-08-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20200820_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
