# Generated by Django 3.0.7 on 2020-08-18 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0010_auto_20200818_2314'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masa', models.CharField(blank=True, editable=False, max_length=20)),
                ('total', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Onaylandı', 'Onaylandı'), ('Yapılıyor', 'Yapılıyor'), ('Çıkarıldı', 'Çıkarıldı'), ('Masada', 'Masada'), ('İptal', 'İptal')], max_length=15)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Onaylandı', 'Onaylandı'), ('Yapılıyor', 'Yapılıyor'), ('Çıkarıldı', 'Çıkarıldı'), ('Masada', 'Masada'), ('İptal', 'İptal')], max_length=15)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('urun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Urun')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
